CREATE TABLE "okataxis_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"category" varchar NOT NULL,
	"price" varchar NOT NULL,
	"car" varchar NOT NULL,
	"distance" varchar,
	"stop_1" varchar,
	"stop_2" varchar,
	"stop_3" varchar,
	"pickup_date" timestamp NOT NULL,
	"pickup_time" varchar NOT NULL,
	"pickup_location" varchar NOT NULL,
	"dropoff_location" varchar NOT NULL,
	"passengers" integer NOT NULL,
	"childs" integer NOT NULL,
	"bags" integer NOT NULL,
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"flight" varchar,
	"payment_id" varchar,
	"hours" integer,
	"minutes" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
