import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({
  weight: ["100","300","400","700","900"],
  subsets:["latin"],
  variable: "--font-roboto",
  display: "swap"

})

export const metadata: Metadata = {
  title: "Spotlimo",
  description: "Generated by Spotlimo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
        >
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
